Employees =[
    {
           Id:1,
        Name:"Alice",
        Department:"Engineering",
        Salary:12000,
        BonusPercentage:15
    },
    {
         Id:2,
        Name:"Charlie",
        Department:"Arts",
        Salary:13000,
        BonusPercentage:10
    },
    {
         Id:3,
        Name:"Arun",
        Department:"Engineering",
        Salary:32000,
        BonusPercentage:20
    },
    {
         Id:4,
        Name:"Ronaldo",
        Department:"Arts",
        Salary:15000,
        BonusPercentage:10
    },
    {
        Id:5,
        Name:"Justin",
        Department:"Engineering",
        Salary:25000,
        BonusPercentage:15
    },
    {
         Id:6,
        Name:"Dave",
        Department:"Arts",
        Salary:65000,
        BonusPercentage:20
    },
    {
        Id:7,
        Name:"Jon",
        Department:"Engineering",
        Salary:45000,
        BonusPercentage:25
    }
    ]
  